name: app

type: php:7.4

runtime:
    extensions:
        - redis
        - apcu
        - mbstring
        - sodium
        - ctype
        - iconv
        - pdo_pgsql
        

build:
    flavor: none

variables:
    php-ext:
        redis: 5.3.1

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

disk: 512

mounts:
    "/var": { source: local, source_path: var }
    "/public/uploads": { source: local, source_path: uploads}
    
hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        
        (>&2 symfony-build)

    deploy: |
        set -x -e

        (>&2 symfony-deploy)

relationships:
        database: "db:postgresql"
        redis: "rediscache:redis"